//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
        public Nullable<System.TimeSpan> LogoutTime { get; set; }
        public Nullable<System.TimeSpan> SpentTime { get; set; }
        public int ReasonID { get; set; }
    
        public virtual Reasons Reasons { get; set; }
    }
}
